version: "3.7"
services:
  ingress:
    build:
      context: .
      dockerfile: Dockerfile-ingress    
    expose:
      - "10004"
      - "9905"
    ports:
      - "10004:10000"
      - "9905:9901"
  egress:
    build:
      context: .
      dockerfile: Dockerfile-egress    
    expose:
      - "10003"
      - "9904"
    ports:
      - "10003:10000"
      - "9904:9901"
      